### ISSUE TITLE
voice toggle 테스트 서버에 올린 후 오류 페이지 뜸 

### ISSUE THREAD

**Issue by IChanHui** [resonance-ai/pulse9#20]
테스트 서버에 올린 후 docker compose up -d 는 모두 오류 없이 잘 진행 됨 
하지만 웹으로는 css?? 디자인이 모두 깨지고 화면이 보이는것 같으네 그것조차도 제대로 나오지 않음

```
ChunkLoadError: Loading chunk 931 failed.
(error: http://34.92.113.73:3000/_next/static/chunks/app/page-ecb9ffa1bdab1418.js)
    at Object.j (webpack-edb4277619bc1179.js:1:3100)
    at webpack-edb4277619bc1179.js:1:1400
    at Array.reduce (<anonymous>)
    at Function.e (webpack-edb4277619bc1179.js:1:1366)
    at 23-c11194b6da339e5b.js:2:18831
    at 23-c11194b6da339e5b.js:2:19033
    at t (23-c11194b6da339e5b.js:2:19236)
```
```
Uncaught Error: Minified React error #423; visit https://react.dev/errors/423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at iZ (fd9d1056-13aa76f036058ae3.js:1:118349)
    at ia (fd9d1056-13aa76f036058ae3.js:1:95162)
    at fd9d1056-13aa76f036058ae3.js:1:94984
    at il (fd9d1056-13aa76f036058ae3.js:1:94991)
    at oJ (fd9d1056-13aa76f036058ae3.js:1:92347)
    at oZ (fd9d1056-13aa76f036058ae3.js:1:91766)
    at MessagePort.T (23-c11194b6da339e5b.js:1:83894)
```
```
Uncaught ChunkLoadError: Loading chunk 931 failed.
(error: http://34.92.113.73:3000/_next/static/chunks/app/page-ecb9ffa1bdab1418.js)
    at Object.j (webpack-edb4277619bc1179.js:1:3100)
    at webpack-edb4277619bc1179.js:1:1400
    at Array.reduce (<anonymous>)
    at Function.e (webpack-edb4277619bc1179.js:1:1366)
    at 23-c11194b6da339e5b.js:2:18831
    at 23-c11194b6da339e5b.js:2:19033
    at t (23-c11194b6da339e5b.js:2:19236)
```

<img width="350" alt="image" src="https://github.com/user-attachments/assets/97a63ed6-af19-4457-b574-7a13a575260b">
<img width="348" alt="image" src="https://github.com/user-attachments/assets/8fb2bc92-d966-4273-8ea5-1feea11a2d3a">

**Comment by IChanHui** [comment]
docker compose up -d 를 다시 실행 해본 결과 여전히 웹으로는 css가 제대로 적용되어있지 않음

**Comment by IChanHui** [comment]
수동으로 명령어 처리한 후 docker compose up -d에서 나오던 오류가 갑자기 괜찮아짐
