### ISSUE TITLE
[voice-toggle-2] run start 에서 모듈을 찾을 수 없다는 오류

### ISSUE THREAD

**Issue by IChanHui** [resonance-ai/pulse9#24]
```shell
2024-10-07 20:41:50 > next-app-template@0.0.1 start
2024-10-07 20:41:50 > next start
2024-10-07 20:41:50 
2024-10-07 20:42:01   ▲ Next.js 14.2.4
2024-10-07 20:42:01   - Local:        http://localhost:3000
2024-10-07 20:42:01 
2024-10-07 20:42:01  ✓ Starting...
2024-10-07 20:42:04  ✓ Ready in 12.7s
2024-10-07 20:42:20  ⨯ Error: Cannot find module '/workspace/.next/server/middleware-manifest.json'
2024-10-07 20:42:20 Require stack:
2024-10-07 20:42:20 - /workspace/node_modules/next/dist/server/next-server.js
2024-10-07 20:42:20 - /workspace/node_modules/next/dist/server/next.js
2024-10-07 20:42:20 - /workspace/node_modules/next/dist/server/lib/start-server.js
2024-10-07 20:42:20 - /workspace/node_modules/next/dist/cli/next-start.js
2024-10-07 20:42:20     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-10-07 20:42:20     at /workspace/node_modules/next/dist/server/require-hook.js:55:36
2024-10-07 20:42:20     at Module._load (node:internal/modules/cjs/loader:981:27)
2024-10-07 20:42:20     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-10-07 20:42:20     at mod.require (/workspace/node_modules/next/dist/server/require-hook.js:65:28)
2024-10-07 20:42:20     at require (node:internal/modules/helpers:177:18)
2024-10-07 20:42:20     at NextNodeServer.getMiddlewareManifest (/workspace/node_modules/next/dist/server/next-server.js:933:26)
2024-10-07 20:42:20     at NextNodeServer.getMiddleware (/workspace/node_modules/next/dist/server/next-server.js:938:31)
2024-10-07 20:42:20     at Server.handleNextDataRequest (/workspace/node_modules/next/dist/server/base-server.js:180:37)
2024-10-07 20:42:20     at Server.normalizeAndAttachMetadata (/workspace/node_modules/next/dist/server/base-server.js:285:39) {
2024-10-07 20:42:20   code: 'MODULE_NOT_FOUND',
2024-10-07 20:42:20   requireStack: [
2024-10-07 20:42:20     '/workspace/node_modules/next/dist/server/next-server.js',
2024-10-07 20:42:20     '/workspace/node_modules/next/dist/server/next.js',
2024-10-07 20:42:20     '/workspace/node_modules/next/dist/server/lib/start-server.js',
2024-10-07 20:42:20     '/workspace/node_modules/next/dist/cli/next-start.js'
2024-10-07 20:42:20   ]
2024-10-07 20:42:20 }
2024-10-07 20:42:24 Error: Cannot find module '/workspace/.next/server/middleware-manifest.json'
2024-10-07 20:42:24 Require stack:
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/next-server.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/next.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/lib/start-server.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/cli/next-start.js
2024-10-07 20:42:24     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-10-07 20:42:24     at /workspace/node_modules/next/dist/server/require-hook.js:55:36
2024-10-07 20:42:24     at Module._load (node:internal/modules/cjs/loader:981:27)
2024-10-07 20:42:24     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-10-07 20:42:24     at mod.require (/workspace/node_modules/next/dist/server/require-hook.js:65:28)
2024-10-07 20:42:24     at require (node:internal/modules/helpers:177:18)
2024-10-07 20:42:24     at NextNodeServer.getMiddlewareManifest (/workspace/node_modules/next/dist/server/next-server.js:933:26)
2024-10-07 20:42:24     at NextNodeServer.getEdgeFunctionsPages (/workspace/node_modules/next/dist/server/next-server.js:949:31)
2024-10-07 20:42:24     at NextNodeServer.renderErrorToResponseImpl (/workspace/node_modules/next/dist/server/next-server.js:908:22)
2024-10-07 20:42:24     at /workspace/node_modules/next/dist/server/base-server.js:2077:25 {
2024-10-07 20:42:24   code: 'MODULE_NOT_FOUND',
2024-10-07 20:42:24   requireStack: [
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/next-server.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/next.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/lib/start-server.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/cli/next-start.js'
2024-10-07 20:42:24   ]
2024-10-07 20:42:24 }
2024-10-07 20:42:24  ⨯ Error: Cannot find module '/workspace/.next/server/pages/_error.js'
2024-10-07 20:42:24 Require stack:
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/require.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/next-server.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/next.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/server/lib/start-server.js
2024-10-07 20:42:24 - /workspace/node_modules/next/dist/cli/next-start.js
2024-10-07 20:42:24     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
2024-10-07 20:42:24     at /workspace/node_modules/next/dist/server/require-hook.js:55:36
2024-10-07 20:42:24     at Module._load (node:internal/modules/cjs/loader:981:27)
2024-10-07 20:42:24     at Module.require (node:internal/modules/cjs/loader:1231:19)
2024-10-07 20:42:24     at mod.require (/workspace/node_modules/next/dist/server/require-hook.js:65:28)
2024-10-07 20:42:24     at require (node:internal/modules/helpers:177:18)
2024-10-07 20:42:24     at requirePage (/workspace/node_modules/next/dist/server/require.js:109:84)
2024-10-07 20:42:24     at /workspace/node_modules/next/dist/server/load-components.js:98:84
2024-10-07 20:42:24     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-10-07 20:42:24     at async loadComponentsImpl (/workspace/node_modules/next/dist/server/load-components.js:98:26) {
2024-10-07 20:42:24   code: 'MODULE_NOT_FOUND',
2024-10-07 20:42:24   requireStack: [
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/require.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/next-server.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/next.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/server/lib/start-server.js',
2024-10-07 20:42:24     '/workspace/node_modules/next/dist/cli/next-start.js'
2024-10-07 20:42:24   ]
2024-10-07 20:42:24 }
```

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/5aa5dc6a-54bc-46f6-a946-a7156a5bade4">

**Comment by IChanHui** [comment]
다시 실행하니 오류 없이 잘 됨 

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/c4548e5c-8f3d-447a-9314-e389f5379d9c">
